pipeline {
  agent {
    docker { 
      image 'ubuntu:22.04' // Specify the desired Ubuntu version
      args '-u root' // Run the container as root
    }
  }
  environment {
    GIT_URL = 'https://github.com/Simha4820/plugins.git'
  }
  stages {
    stage('Checkout Code') {
      steps {
        // Checkout the app from GitHub
        git branch: 'main', url: "${GIT_URL}"
      }
    }
    stage('Test') {
      steps {
        // Check Python version
        sh 'python3 --version'
      }
    }
    stage('Run App') {
      steps {
        // Run the app in detached mode
        sh "python3 app.py"
      }
    }
  }
}
